name: Run bot.py Python script

on:
  schedule:
    - cron: '47 6 * * *'   # 12:17 PM IST (06:47 AM UTC)
    - cron: '25 10 * * *'  # 03:55 PM IST (10:25 AM UTC)
    - cron: '55 13 * * *'  # 07:25 PM IST (01:55 PM UTC)
    - cron: '25 16 * * *'  # 09:55 PM IST (04:25 PM UTC)
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-telegram-bot
      
      - name: Run Python script
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: python bot.py
