name: Run bot.py Python script

on:
  schedule:
    - cron: '30 3 * * *'  # 09:00 AM IST (03:30 AM UTC)
    - cron: '30 12 * * *' # 06:00 PM IST (12:30 PM UTC)
    - cron: '30 15 * * *' # 09:00 PM IST (03:30 PM UTC)
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-telegram-bot
      
      - name: Run Python script
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: python bot.py
