name: Run bot.py Python script

on:
  schedule:
    - cron: '20 7 * * *'   # 12:50 PM IST (07:20 AM UTC)
    - cron: '50 10 * * *'  # 04:20 PM IST (10:50 AM UTC)
    - cron: '50 14 * * *'  # 08:20 PM IST (02:50 PM UTC)
    - cron: '50 16 * * *'  # 10:20 PM IST (04:50 PM UTC)
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-telegram-bot
      
      - name: Run Python script
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: python bot.py
